services:
  - type: web
    name: cinevault
    runtime: python
    plan: free
    branch: main
    autoDeployTrigger: commit
    buildCommand: ./build.sh
    startCommand: gunicorn TuPrimeraPaginaLeivaCecchi.wsgi:application
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        sync: false
